//
//  MagnetometerSensor.swift
//  SensorApp
//
//  Copyright © 2016 Zühlke Engineering AG. All rights reserved.
//

import CoreMotion

/**
 The purpose of the `MagnetometerSensor` class is to provide the data that is generated by the magnetometer of the device.
 For details of this sensor see https://en.wikipedia.org/wiki/Magnetometer
 
 The `MagnetometerSensor` class is a subclass of the `AbstractSensor`, and it conforms to the `DeviceSensor` protocol.
 */
class MagnetometerSensor: AbstractSensor, DeviceSensor {

    fileprivate weak var manager : CMMotionManager?
    
    /// A Bool that indicates that the magnetometer is available on the device
    var isAvailable : Bool{
        
        get{
            guard let manager = manager else {return false}
            return manager.isMagnetometerAvailable
        }
    }
    
    /// The type of class is Magnetometer
    var type : SensorType {
        get{
            return .Magnetometer
        }
    }
    
    /**
     Public initializer that takes `CMMotionManager` and `FileWriterService` as an argument.
     `CMMotionManager` must be injected because Apple recommends to have only one instance of it for performance reasons as it is used in multiple sensor classes.
     `FileWriterService` is used to save the measured results.
     */
    init(motionManager: CMMotionManager, fileWriterService: FileWriterService) {
        super.init(fileWriterService: fileWriterService, deviceType: .Magnetometer)
        manager = motionManager
    }
    
    /**
     Method to start the reporting of sensor data. The data is read with the interval specified by `magnetometerUpdateInterval`
     */
    func startReporting(){
        guard isAvailable else {
            print("MagnetometerSensor not available")
            return
        }
        
        guard let manager = manager else {return}
        
        _isReporting = true
        
        manager.magnetometerUpdateInterval = 0.1
        manager.startMagnetometerUpdates(to: OperationQueue()) { (data:CMMagnetometerData?, error: Error?) in
            self.persistData(data)
        }
    }
    
    ///method that writes the data from the sensor into a dictionary structur for later JSON generation
    fileprivate func persistData(_ data: CMMagnetometerData?){
        
        guard let data = data else {return}
        
        var params = [String:AnyObject]()
        params["type"] = "Magnetometer" as AnyObject?
        params["date"] = dateFormatter.string(from: Date()) as AnyObject?
        params["x"] = data.magneticField.x as AnyObject?
        params["y"] = data.magneticField.y as AnyObject?
        params["z"] = data.magneticField.z as AnyObject?
        
        fileWriter?.addLine(params)
    }
    
    ///method that stops sensor reading and generation of data
    func stopReporting(){
        guard let manager = manager else {return }
        manager.stopMagnetometerUpdates()
        _isReporting = false
    }
    
}
